#---
#
#spring:
#  profiles: in-memory
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:default
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
##
##
##---
##
##spring:
##  profiles: cloud
##  datasource:
##    driver-class-name: org.postgresql.Driver
##  jpa:
##    hibernate:
##      ddl-auto: create
##    properties:
##      hibernate:
##        dialect: org.hibernate.dialect.PostgreSQL9Dialect
