package com.blogger.blogcast.repository;

import com.blogger.blogcast.model.Comment;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

/**
 * I need to tighten this up
 * the @Query annotation could probably be replaced with a fancy Spring method (long method name generated by spring)
 */

@Repository
public interface CommentRepository extends CrudRepository<Comment, Long> {
    Iterable<Comment> getCommentsByBlogEntryId(Long blogEntryId);
}
